language: java

jdk:
  - oraclejdk8
os:
  - linux

services:
  - docker


before_install:
  - "echo 'MAVEN_OPTS = $MAVEN_OPTS'"
  - docker build -t juakinggg/pollrest .
  - docker run -d -p 127.0.0.1:8080:8080 juakinggg/pollrest
  - docker ps -a
  - curl -X GET http://localhost:8080/v1/polls/site1
  - curl -X GET http://127.0.0.1:8080/v1/polls/site1


sudo: required

# override default .mvnw
install: true

script: mvn install
