language: java
jdk:
  - oraclejdk8
os:
  - linux
services:
  - docker


before_install:
  - docker build -t juakinggg/pollrest .
  - docker run -d -p 127.0.0.1:8080:8080 juakinggg/pollrest
  - docker ps -a
  
sudo: required

install: true

script: ./mvnw install
